### ISSUE TITLE
asking about dataset

### ISSUE THREAD

**Issue by isabelle-le** [HuiZhangDB/PMEmo#1]
Hi HuiZhangDB, 
greatwork to you and the team. I am looking the dataset for my school study purpose. However the dataset is not avaiable to download via the link in your blog post. Could you please  provide me a different way to access the dataset. Great thanks and have a nice weekend.
Isa
isabelle.le@yahoo.com
![image](https://user-images.githubusercontent.com/32997231/57177024-159c6e80-6e60-11e9-86f8-b8d17da73674.png)

**Comment by HuiZhangDB** [comment]
Hi Isa, if the website is still not available I'll send you the dataset by email tonight. Wish you all the best with your ongoing research.

**Comment by HuiZhangDB** [comment]
> Hi HuiZhangDB,
> greatwork to you and the team. I am looking the dataset for my school study purpose. However the dataset is not avaiable to download via the link in your blog post. Could you please provide me a different way to access the dataset. Great thanks and have a nice weekend.
> Isa
> [isabelle.le@yahoo.com](mailto:isabelle.le@yahoo.com)
> ![image](https://user-images.githubusercontent.com/32997231/57177024-159c6e80-6e60-11e9-86f8-b8d17da73674.png)

Hi Isa, if the website is still not available I'll send you the dataset by email tonight. Wish you all the best with your ongoing research.

**Comment by isabelle-le** [comment]
Hi Zhang, Thank you for your response. Please share with me your dataset. I want to test it with my model, i think the problem is my current dataset. It is too small to have a good prediction. I am waiting for your data. 
Thanks and have a great day,
-------------------------------------------------------------------------------------Isabelle LEMaster in Business Analytics and Big data
Ecole internationale des sciences du traitement del'information école d’ingénieurs mathématiques-informatiqueAvenue du parc 95000 Cergy-Pontoise cedexTél: + 33 (0)7 69 33 16 79------------------------------------------------------------------------------------- 

    On Wednesday, May 8, 2019, 6:21:22 AM GMT+2, Mia Zhang <notifications@github.com> wrote:  
 
 
Hi Isa, if the website is still not available I'll send you the dataset by email tonight. Wish you all the best with your ongoing research.

**Comment by HuiZhangDB** [comment]
I have uploaded the dataset into Google Drive. You can get access to it by the following link: https://drive.google.com/open?id=1qDk6hZDGVlVXgckjLq9LvXLZ9EgK9gw0

**Comment by ShristiBisht** [comment]
Thank you so much
