### ISSUE TITLE
Can ISRC be included in metadata? 

### ISSUE THREAD

**Issue by winter1pm** [HuiZhangDB/PMEmo#2]
Metadata of tracks, e.g. title, displayed artist, are usually ambiguous. Could your team add "ISRC" of tracks as one attribute of the metadata? If so, the dataset will be more useful for users with access to many full length audios. 

btw: some songs have comma symbol in their artist attribute. It causes trouble to csv parser. Could your team fix it? 

Thanks very much.

**Comment by HuiZhangDB** [comment]
Thanks for the suggestion. But we can't get the ISRC codes of the tracks. Please try accessing the full-length audios by the song title and artist.

btw: please use [the updated version of PMEmo (2019)](https://drive.google.com/drive/folders/1qDk6hZDGVlVXgckjLq9LvXLZ9EgK9gw0), we fixed the metadata and it's easy to be loaded using pandas.DataFrame.
